name: build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Test
        run: go test ./...
      - name: Update go.mod
        if: success()
        run: |
          sed -i -e '/trek10inc\/awsets v/ s/ v.*/ v'"$TAG"'/' cmd/awsets/go.mod
        env:
          TAG: ${{ github.event.release.tag_name }}
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add cmd/awsets/go.mod
          git commit -m "Update version in go.mod"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: ${{ github.event.release.tag_name }}
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}